# Generated by Django 4.1 on 2025-06-20 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idcategoria', models.CharField(max_length=100)),
                ('nombre', models.TextField()),
                ('descripcion', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(max_length=100)),
            ],
        ),
    ]
